### ISSUE TITLE
Suggestion: a Fork for "Principia for TRAPPIST-1"?

### ISSUE THREAD

**Issue by Growflavor** [KSP-RO/RSSTimeFormatter#11]
What would be needed to have this 'work' with epoch "JD2457000.000000000" =  UTC Noon  Monday 2014 December 08...This is the epoch that Principia uses for their .cfg for the SLIPPIST-1 system making it a model of TRAPPIST-1 apparently with transit timing accuracy on the order of a minute.   I am currently a bit rusty with code so am not quite following where epoch comes from in "DateTime epoch = GetEpoch();" for example... Thanks for your insights as to if this is more likely a few 'simple' changes or a complex modification of the current code!

This tool already does a beautiful job showing the correct UTC for Principia RSS eclipses.  At least my imagination would enjoy doing the same with the TRAPPIST-1 system.  For me anyway there is something inspiring seeing on my screen the current time of planets transiting & rotating in hours around their Sun seen 'today' on Earth as they were ~40 years ago in their own solar system.

**Comment by jwvanderbeck** [comment]
You can use any custom epoch you want by editing the config
