### ISSUE TITLE
unable to load saves

### ISSUE THREAD

**Issue by Aurora-StFM** [KSP-RO/RSSTimeFormatter#21]
[KSPLOG.zip](https://github.com/KSP-RO/RSSTimeFormatter/files/12300291/KSPLOG.zip)
after installing, all saves disappear from the saves menu
![image](https://github.com/KSP-RO/RSSTimeFormatter/assets/84717132/d6a0c946-93a5-424e-9b8d-34ad4cb14dfa)

**Comment by siimav** [comment]
Try moving all saves outside the \Saves\ folder and creating a new one in case any of them is corrupt.
If that doesn't work then I couldn't help but notice that your RP-1 install contains **many** mods we do not support. Please follow the official install guide here: https://github.com/KSP-RO/RP-1/wiki/RO-&-RP-1-Express-Installation-for-1.12.3
