### ISSUE TITLE
Days are not years

### ISSUE THREAD

**Issue by ec429** [KSP-RO/RSSTimeFormatter#4]
In PrintDateDelta,

https://github.com/KSP-RO/RSSTimeFormatter/blob/651df67ae983ded124b056168d686cb825fa66a1/RSSTimeFormatter/RSSTimeFormatter.cs#L191

This is the count of days, but is given the unit "years".

**Comment by siimav** [comment]
Fixed in 14ff43d5a52daba9cf8e44457a1c50b1730261c0
